### ISSUE TITLE
Allow default case to return/break/continue

### ISSUE THREAD

**Issue by haltcase** [alehander92/gara#18]
Currently you can't use the default case for control flow (ie. `return`) which is for example a common pattern to basically extract a value if there's a match or bail otherwise.

```nim
import gara, options

let opt = some 10

proc foo () =
  let val = match opt:
    Some(@a): a * 2
    _: return

  # do stuff with `val`
```

**Comment by alehander92** [comment]
Sorry, I don't think return is a good idea: `let val = ..` implies the expression will always return a valid value which will always be assigned to `val`. It would be not nice at all to break that, especially in a longer expession.

In your case, you can assign locally: `Some(@a): val = a * 2` and return later. This is exactly how `if` / `case` work too.

**Comment by haltcase** [comment]
Fair enough if you'd like to keep it as is but Rust's `match` works this way:

```rust
fn main() {
    let a = match "four" {
        "one" => 1,
        "two" => 2,
        _ => return
    };
    
    println!("a = {}", a); // never reached
}
```

**Comment by alehander92** [comment]
It's hard to implement and it behaves differently than e.g. case as expression: I'd prefer to not do it for now
