### ISSUE TITLE
Run-time check for type mismatch, could not be compile-time?

### ISSUE THREAD

**Issue by Leu-Gim** [alehander92/gara#3]
```nim
import gara
type Rectangle = object
      a, b: int
let a = @[Rectangle(a: 1, b: 2), Rectangle(a: 3, b: 4), Rectangle(a: 5, b: 6), Rectangle(a: 7, b: 8)]
match(a):
of @[int @first, _, *(a: @list)]: # mismatching `int` added to make it fail
  echo first, list
```
Nim's seq cannot have different types values, at least with `int` and an object/tuple it's always wrong,
so principally can be caught at compile-time. Not to compile for patterns which can never match. ?

**Comment by alehander92** [comment]
Detecting that this is in fact impossible to be true in cases like that means `gara` does additional typechecking and I really want to go down that road only if really needed.

Also writing a pattern like that is like writing 

```nim
if a[0] is int:
```
You wouldn't expect Nim to fail to compile this, right?

**Comment by Leu-Gim** [comment]
```nim
if a[0] is int:
```
No, wouldn't, this code looks ok.
```nim
let a = @[0, Rectangle(a: 5, b: 7)]
```
This doesn't look ok. :) Will fail seems for any definition of `Rectangle`.

**Comment by alehander92** [comment]
Well 
```
of @[0, Rectangle(a: 5, b: 7)]
```

should already fail on compile time, just without a good enough error message. However that's a different case
