### ISSUE TITLE
"match ... of" sounds off

### ISSUE THREAD

**Issue by narimiran** [alehander92/gara#6]
When using `case` in regular Nim it reads ok: `case a of: x, y, z`. But the sentence `match a of: x, y, z` sounds wrong. A better variant would be to use "with": `match a with: x, y, z`.

---

Btw, this is subjective but I really like the syntax F# is using:
```fsharp
let printColorName (color: Color) =
    match color with
    | Color.Red -> printfn "Red"
    | Color.Green -> printfn "Green"
    | Color.Blue -> printfn "Blue"
    | _ -> ()
```

There is only one "with" at the beginning, not for each case like it is in Nim with "of". 

---

1. Does Nim allow to change "of" to "with"? If so, would you consider using it?
2. Does Nim allow to have "of"/"with" just on the first line, not for every case? 

Both combined would produce something like this (taken from the readme):
```nim
match(a) with:
  Rectangle: # matches Rectangle(a: 0), Rectangle(a: 2, b: 4)
    echo "rectangle"
  else:
    echo "other"
```

**Comment by alehander92** [comment]
Actually the easiest thing would be to have it like patty: directly listing the branches 

```nim
match(a):
  Rectangle:
    echo "rectangle"
  _:
    echo "other"
```

I used `of` mostly because it seemed to me as a good idea to have the same syntax as `case`, I liked that in ast_pattern_matching . I also think Araq (maybe other people) expect that, as he even wondered if we can make 
```nim
match(a) # without colon
of .. 
```
work

Now, your arguments make sense: but I think we can skip `with` and directly list the branches, I feel if people read it literally they will still say it automatically.

**Comment by narimiran** [comment]
> ```nim
> match(a):
>  Rectangle:
>    echo "rectangle"
>  _:
>    echo "other"
> ```

This looks very nice and clean to me! 

> I think we can skip `with` and directly list the branches

I'm fine with this — I'll add "with" in my head. (But I cannot remove that strange "of" once I've seen it in code)

---

> ```nim
> match(a) # without colon
> of .. 
> ```

I personally dislike this style where `of` is on the same indentation level as `case`/`match`, but I know that I'm in minority and that is a recommended style.

**Comment by haltcase** [comment]
This depends a lot on how closely `match` and `case` should be related. If they're too closely related will there be confusion on which supports what set of features? If so the syntax being different would reinforce that they are different constructs.

I like the form without `of` slightly more but both are fine.

@narimiran 

> I personally dislike this style where `of` is on the same indentation level as `case`/`match`

It's really no different from F#'s match + `|` that you liked in the OP:

```fsharp
let printColorName (color: Color) =
    match color with
    | Color.Red -> printfn "Red"
    | Color.Green -> printfn "Green"
    | Color.Blue -> printfn "Blue"
    | _ -> ()
```

This would be equivalent in Nim to:

```nim
proc printColorName (color: Color) =
  match color:
  of Color.Red: echo "Red"
  of Color.Green: echo "Green"
  of Color.Blue: echo "Blue"
  else: discard
```

**Comment by narimiran** [comment]
> This would be equivalent in Nim to:

If we're nitpicking, the blocks following the line which ends with `:` should be indented (see `for`, `if`, etc.) ;)

Yeah, I know `of` and `|` are "equivalent", but `|` is so different than a regular character so I can visually very easily tell where the `match` block ends.  
In Nim not only we don't use a special/distinct character, but we have both `of` and `else` which make things even worse.

As the example of "not distinguished enough, consider this:

```nim
match color:
of Color.Red: echo "Red"
of Color.Green: echo "Green"
of Color.Blue: echo "Blue"
if Color ....
```

If you're not careful enough, you might not noticed that the last line is `if` which has nothing to do with `match`.

Compared to indented Nim:
```nim
match color:
  of Color.Red: echo "Red" 
  of Color.Green: echo "Green"
  of Color.Blue: echo "Blue"
if Color ....
```
or F#:
```fsharp
match color with
| Color.Red -> printfn "Red"
| Color.Green -> printfn "Green"
| Color.Blue -> printfn "Blue"
if Color ...
```

**Comment by haltcase** [comment]
Well that's just two bad styles becoming an even worse style, put an empty line there! :smile:

> If we're nitpicking, the blocks following the line which ends with `:` should be indented (see `for`, `if`, etc.) ;)

Well that's arguable, if it's something like a single expression having it on one line is usually fine in `if` or `case`/`match` IMO. But I was really just matching up the two languages to show their rough equivalence.

`of`-free `match` would probably be my vote.

**Comment by munael** [comment]
How is it reconciled with the `case` macros in 0.19?

**Comment by alehander92** [comment]
@narfanar I prefer the current approach compared to the caseStmtMacro system: I've tried to summarize some of my reasons here, but it was a part of a bigger discussion, so ping me if something is not understandable https://gist.github.com/alehander42/2bd15a289432f7f7832a02b1e064f6ab

**Comment by alehander92** [comment]
ok @narimiran , this is now of-free!
